vld:
  - name: mgmtnet
    vim-network-name: internal
additionalParamsForVnf:
  - member-vnf-index: free5gc_upf
    additionalParamsForKdu:
      - kdu_name: free5gc_upf
        additionalParams:
          global:
            projectName: free5gc
            userPlaneArchitecture: single  # possible values are "single" and "ulcl"
            uesubnet: 10.7.230.0/24
            n4network:
              enabled: true
              name: n4network
              type: ipvlan
              masterIf: ens3
              subnetIP: 10.100.50.240
              cidr: 29
              gatewayIP: 10.100.50.246
              excludeIP: 10.100.50.246
            n3network:
              enabled: true
              name: n3network
              type: ipvlan
              masterIf: ens3
              subnetIP: 10.100.50.232
              cidr: 29
              gatewayIP: 10.100.50.238
              excludeIP: 10.100.50.238
            n6network:
              enabled: true
              name: n6network
              type: ipvlan
              masterIf: ens3
              subnetIP: 10.7.230.0
              cidr: 24
              gatewayIP: 10.7.230.1
              excludeIP: 10.7.230.254
            n9network:
              enabled: true
              name: n9network
              type: ipvlan
              masterIf: ens3
              subnetIP: 10.100.50.224
              cidr: 29
              gatewayIP: 10.100.50.230
              excludeIP: 10.100.50.230
          upf:
            name: upf
            replicaCount: 1
            image:
              name: free5gc/upf
              tag: v4.0.0
              pullPolicy: Always
            configmap:
              wrapperAdditionalCommands: ""
              # wrapperAdditionalCommands: |
              #   echo "123" > /tmp/123
            volume:
              mount: /free5gc/config/
              tlsmount: /free5gc/config/TLS

            # network paramters
            n3if:  # GTP-U
              ipAddress: 10.100.50.233
            n4if:  # PFCP
              ipAddress: 10.100.50.241
            n6if:  # DN
              ipAddress: 10.7.230.203

            podAnnotations: {}
              # additional annotations
            imagePullSecrets: []
            podSecurityContext: {}
            securityContext:
              capabilities:
                add: ["NET_ADMIN"]
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
            readinessProbe:
              initialDelaySeconds: 0
              periodSeconds: 1
              timeoutSeconds: 1
              failureThreshold:  40
              successThreshold: 1
            livenessProbe:
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
              failureThreshold: 3
              successThreshold: 1
            nodeSelector: {}
            tolerations: []
            affinity: {}
            autoscaling:
              enabled: false
              minReplicas: 1
              maxReplicas: 100
              targetCPUUtilizationPercentage: 80
              # targetMemoryUtilizationPercentage: 80
            configuration:
              dnnList: # The DNN list supported by UPF
                - dnn: internet # Data Network Name
                  cidr: 10.1.0.0/17 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
                  # natifname: n6
                - dnn: internet # Data Network Name
                  cidr: 10.1.128.0/17 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
                  # natifname: n6

              logger: # log output setting
                enable: true # true or false
                level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
                reportCaller: false # enable the caller report or not, value: true or false

          # The followed values will be considered in the case of choosing "ulcl" architecture for the user plane