name: Deploy functions
on:
  workflow_dispatch:
    inputs:
      cluster_ip:
        required: true
        type: string

jobs:
  ondemand-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/proxy.key
          chmod 600 ~/.ssh/proxy.key
          echo "$QEMU_KEY" > ~/.ssh/qemu.key
          chmod 600 ~/.ssh/qemu.key
          echo "$GIT_KEY" > ~/.ssh/git.key
          chmod 600 ~/.ssh/git.key
          cat >>~/.ssh/config <<END
          Host proxy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/proxy.key
            StrictHostKeyChecking no
            Port $SSH_PORT
          Host osm
            HostName $OSM_HOST
            IdentityFile ~/.ssh/qemu.key
            StrictHostKeyChecking no
            ProxyJump proxy
          Host cluster
            HostName $CLUSTER_HOST
            StrictHostKeyChecking no
            ProxyJump proxy
          END

      - name: Deploy functions
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.SSH_PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          script: |
            #export OSM_HOSTNAME=nbi.10.7.230.201.nip.io 
            #echo "${{ secrets.config }}" | base64 -d > config5gc.yaml
            #osm ns-create --ns_name free5gc --nsd_name free5gc_ns --vim_account dummy --config_file config5gc.yaml
            echo "${{ inputs.cluster_ip }}"
