name: Deploy functions
on:
  workflow_dispatch:
    inputs:
      cluster_ip:
        required: true
        type: string

jobs:
  ondemand-test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy functions
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.SSH_PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          script: |
            export OSM_HOSTNAME=nbi.10.7.230.201.nip.io 
            echo "${{ secrets.config }}" | base64 -d > config5gc.yaml
            osm ns-create --ns_name free5gc --nsd_name free5gc_ns --vim_account dummy --config_file config5gc.yaml
            echo "${{ inputs.cluster_ip }}"
